# -*- coding: utf-8 -*-
"""Analise_Associativa_11/04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GzvNjkfHyDyVIF68-yITq0z70NYPSaKp
"""

import numpy as np
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules

dados = pd.read_excel('Online_Retail.xlsx')
dados.head()

#Retirar os espaços extras nas descrições
dados['Description'] = dados['Description'].str.strip()

#Retirar os registros sem "Invoice Number"
dados.dropna(axis=0, subset=['InvoiceNo'], inplace=True)
dados = dados.reset_index(drop=True)

#Transformar as colunas "Invoice Number" em string
dados['InvoiceNo'] = dados['InvoiceNo'].astype('str')

#Eliminando as transações feitas no cartão de crédito que possuem problema
dados = dados[~dados['InvoiceNo'].str.contains('C')]

franca = dados[dados['Country'] == 'France']
franca.reset_index(drop=True)

compra_franca_detalhado = franca.groupby(['InvoiceNo', 'Description'])['Quantity']
compra_franca_detalhado.head()

compra_franca_detalhado = compra_franca_detalhado.sum()
compra_franca_detalhado.head()

compra_franca_detalhado = compra_franca_detalhado.unstack()
compra_franca_detalhado.head()

compra_franca_detalhado = compra_franca_detalhado.fillna(0)
compra_franca_detalhado.head()

compra_franca_detalhado['10 COLOUR SPACEBOY PEN'].unique()

def hot_encode(x):
  if x <= 0:
    return 0
  if x >= 1:
    return 1

compras_encoded = compra_franca_detalhado.applymap(hot_encode)
compras_encoded['10 COLOUR SPACEBOY PEN'].unique()

itens_frequentes = apriori(compras_encoded, min_support = 0.05, use_colnames=True)
regras = association_rules(itens_frequentes, metric='lift', min_threshold=1)
regras = regras.sort_values(['confidence', 'lift'], ascending=[False,False])
regras